### ISSUE TITLE
Trying to trouble shoot

### ISSUE THREAD

**Issue by hellofantastic** [ravinderk/wp-chrome-logger#2]
Installed the plugin and activated, in wp 3.9.1, I have chrome logger installed and enabled
I used
ChromePhp::log("hi") ; in a function in functions.php and nothing happens in console
i tested a
ChromePhp::log("hi") or die("nope");

and nope gets printed so ChromePHP isn;t available?

**Comment by jacquesletesson** [comment]
Did you install the Chrome Extension : https://chrome.google.com/webstore/detail/chrome-logger/noaneddfkdjfnfdakjjmocngnfkfehhd/related

**Comment by ravinderk** [comment]
@hellofantastic  plugin updated, i also added installation info.
