### ISSUE TITLE
Doesn't work for ADMIN debugging

### ISSUE THREAD

**Issue by jacquesletesson** [ravinderk/wp-chrome-logger#3]
It seems that the plugin doesn't work for backend. 

Works smoothly on front-end though.

**Comment by ravinderk** [comment]
@jacquesletesson it will not work on backend, i made it like that, but i update it soon to work on backed properly. :+1:

**Comment by jacquesletesson** [comment]
If you need help, let me know.

J.

**Comment by ravinderk** [comment]
@jacquesletesson  plugin updated, now it will work for you in WordPress backend

**Comment by jacquesletesson** [comment]
Will test it and let you know. Thanks man.

**Comment by jacquesletesson** [comment]
Works perfectly! Thanks @ravinderk
